### ISSUE TITLE
Received error message using example code

### ISSUE THREAD

**Issue by simzn** [DereWah/Skript-GPT#3]
![Screen Shot 2023-07-12 at 10 50 14 PM](https://github.com/DereWah/Skript-GPT/assets/86796207/9123b904-1b56-4b02-894d-f911880a9749)

`[02:48:45 WARN]: [Skript] Plugin Skript v2.6.4 generated an exception while executing task 2886

java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.openai.com/v1/chat/completions

	at org.derewah.skriptgpt.effects.EffChatCompletionRequest.execute(EffChatCompletionRequest.java:115) ~[Skript-GPT-1.1.jar:?]

	at ch.njol.skript.util.AsyncEffect.lambda$walk$1(AsyncEffect.java:60) ~[Skript-2.6.4.jar:?]

	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]

	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-307]

	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]

	at java.lang.Thread.run(Thread.java:833) ~[?:?]

Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.openai.com/v1/chat/completions

	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]

	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]

	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]

	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]

	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]

	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2051) ~[?:?]

	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2046) ~[?:?]

	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]

	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2045) ~[?:?]

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609) ~[?:?]

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]

	at org.derewah.skriptgpt.util.HttpRequest.main(HttpRequest.java:92) ~[Skript-GPT-1.1.jar:?]

	at org.derewah.skriptgpt.effects.EffChatCompletionRequest.execute(EffChatCompletionRequest.java:108) ~[Skript-GPT-1.1.jar:?]

	... 7 more

Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.openai.com/v1/chat/completions

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2000) ~[?:?]

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]

	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) ~[?:?]

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) ~[?:?]

	at org.derewah.skriptgpt.util.HttpRequest.main(HttpRequest.java:88) ~[Skript-GPT-1.1.jar:?]

	at org.derewah.skriptgpt.effects.EffChatCompletionRequest.execute(EffChatCompletionRequest.java:108) ~[Skript-GPT-1.1.jar:?]

	... 7 more`
	
This error message was generated after running the command "/completion What does completion mean?" using the /completion example code from skript hub docs.

**Comment by DereWah** [comment]
Hello, this is an issie on your side. The plugin says you're getting error 401, unauthorized, therefore I believe you're out of tokens / you did not setup your auth key?
